version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # uninstall Node.js v10 from CodeBuild's image
      - yes | n uninstall

      # install Node.js v12
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - apt-get update
      - echo Installing additional packages
      - apt-get -y install dpkg-sig lintian fakeroot mongodb-server
      - echo Starting mongodb server
      - service mongodb start
  pre_build:
    commands:
      # run npm install using versions in package-lock.json
      - npm ci
  build:
    commands:
      
      # run the build
      - node app.js
artifacts:
  files:
    # bundle everything as a build artifact, except hidden files
    - '**/*'
